services:
  keycloak:
    networks:
      - mm
    ports:
      - "8086:8080"
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev

networks:
  mm:
    driver: bridge
