services:
  keycloak:
    #networks:
    #  - mm
    network_mode: host
    ports:
      - 127.0.0.1:8080:8080
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev

      #go-server:
      #  image: golang:1.22rc2-alpine
      #  container_name: go-server
      #  depends_on: 
      #        - keycloak
      #  networks:
      #    - mm
      #  command: sh -c "go build -o go-server && ./go-server"
      #  ports:
      #    - "8081:8081"
      #  working_dir: /app
      #  volumes:
      #    - ../:/app

networks:
  mm:
    driver: bridge
